### ISSUE TITLE
Extension gives error 'base' key is required when base is defined in a stage

### ISSUE THREAD

**Issue by stromseng** [Vanilla-OS/vib-vscode-ext#1]
The start of my recipe.yml is as follows.
```
# vib
name: my-vanilla-image # Replace this name with your image name
id: my-vanilla-image # Replace this ID with your image ID
stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
    singlelayer: false
    labels:
      maintainer: self-maintained # Optionally, Replace this with your name
    args:
      DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive
```
I get the error `The 'base' key is required in a Vib recipe.(base-missing)` on the second line. Even though it is clearly defined within the first stage.

Reproduce:
1. Clone official vib template at https://github.com/Vanilla-OS/custom-image/tree/main
2. Add #vib to the top of the file
